
# call make to generate README.md

* erpnext-api-client

This is a Haskell API client for
[[https://github.com/frappe/erpnext][ERPNext]]. It aims to be a
light-weight library based on
[[https://hackage.haskell.org/package/http-client][http-client]] and
user-provided record types.

ERPNext has the concept of
[[https://docs.frappe.io/erpnext/user/manual/en/doctype][DocTypes]]
which model entities like Customer, Sales Order, etc.

The [[https://docs.frappe.io/framework/user/en/api/rest][ERPNext REST
API]] basically has seven types of requests covering CRUD operations,
remote method calls, and file uploads.

For CRUD operations on a given DocType there are:

- =GET= list of all documents of a DocType (=getDocTypeList=)
- =POST= to create a new document (=postDocType=)
- =GET= a document by name (=getDocType=)
- =PUT= to update a document by name (=putDocType=)
- =DELETE= a document by name (=deleteDocType=)

Note: Remote method calls and file uploads are not yet supported.

DocTypes in ERPNext can be extended and newly created by users. This is
why this library does not come with any predefined types for DocTypes.
Instead, users can provide their own types with only the fields they
need.

This library provides tooling to generate Haskell record types from a
simple DSL to define DocTypes (very similar to
[[https://hackage.haskell.org/package/persistent/docs/Database-Persist-Quasi.html][persistent's
model definition syntax]]).

** Usage

# Create example file from emacs with: org-babel-tangle

#+begin_src haskell :tangle example1.hs

import ERPNext.Client
import Data.Aeson

data Customer
  { name :: Text
  }

instance FromJSON Customer
instance ToJSON Customer

instance IsDocType Customer where
  docTypeName = "Customer"

main :: IO ()
main = do
  config = mkConfig "https://erpnext.example.com" "api-key" (mkSecret "api-secret")
  c <- getDocType config "theCustomerId" :: IO Customer
  putStrLn $ name c
#+end_src

#+begin_src sh
  stack runhaskell example1.hs
#+end_src

#+RESULTS:
