
# call make to generate README.md

* erpnext-api-client

This is a Haskell API client for
[[https://github.com/frappe/erpnext][ERPNext]]. It aims to be a
light-weight library based on
[[https://hackage.haskell.org/package/http-client][http-client]] and
user-provided record types.

ERPNext has the concept of
[[https://docs.frappe.io/erpnext/user/manual/en/doctype][DocTypes]]
which model entities like Customer, Sales Order, etc.

The [[https://docs.frappe.io/framework/user/en/api/rest][ERPNext REST
API]] basically has seven types of requests covering CRUD operations,
remote method calls, and file uploads.

CRUD operations on a given DocType are:

- =GET= list of all documents of a DocType (=getDocList=)
- =POST= to create a new document (=postDoc=)
- =GET= a document by name (=getDoc=)
- =PUT= to update a document by name (=putDoc=)
- =DELETE= a document by name (=deleteDoc=)

Note: Remote method calls and file uploads are not yet supported.

In ERPNext, DocTypes can be extended and newly created by users. This is
why this library does not come with any predefined types for DocTypes.
Instead, users can provide their own types with only the fields they
need.

This library also provides tooling to generate Haskell record types
for DocTypes from a simple DSL (see section below).

** Usage

This sample code makes a GET request for a named document of the
given DocType.

# Create example file from emacs with: org-babel-tangle

#+begin_src haskell :tangle example1.hs
  {-# LANGUAGE OverloadedStrings #-}

  import ERPNext.Client
  import System.Environment
  import Data.Text (pack)
  import Network.HTTP.Client.TLS
  import Data.Aeson
  import GHC.Generics

  data Customer = Customer
    { name :: String
    } deriving Generic

  instance FromJSON Customer
  instance IsDocType Customer where
    docTypeName = "Customer"
    docName = error "not implemented"

  main :: IO ()
  main = do
    url <- pack <$> getEnv "ERPNEXT_BASE_URL" -- e.g. "https://my-erpnext.frappe.cloud/api"
    apiKey <- pack <$> getEnv "ERPNEXT_API_KEY"
    apiSecret <- mkSecret . pack <$> getEnv "ERPNEXT_API_SECRET"

    let config = mkConfig url apiKey apiSecret
    manager <- newTlsManager
    response <- ERPNext.Client.getDoc manager config "Company A" :: IO (ApiResponse Customer)
    case response of
      Ok _ _ c -> putStrLn $ name c
      Err r _  -> putStrLn $ show r
#+end_src

For running the example, define these variables in a =.env= file:

#+begin_src sh
  export ERPNEXT_BASE_URL=https://my-test.frappe.cloud/api
  export ERPNEXT_API_KEY=xxxxxx
  export ERPNEXT_API_SECRET=yyyyyy
#+end_src

Then, inside this repository directory you can run:

#+begin_src sh
  . .env
  stack runhaskell --package http-client-tls example1.hs
#+end_src

#+RESULTS:

** Interactive testing in GHCi

: . .env
: stack ghci --package http-client-tls

#+begin_src haskell
  {-# LANGUAGE OverloadedStrings #-}
  import ERPNext.Client qualified as Client
  import ERPNext.Client.Simple qualified as Simple
  import ERPNext.Client.QueryStringParam
  import ERPNext.Client.Filter
  import Network.HTTP.Client.TLS
  import System.Environment
  import Data.Aeson
  import GHC.Generics

  url <- pack <$> getEnv "ERPNEXT_BASE_URL"
  apiKey <- pack <$> getEnv "ERPNEXT_API_KEY"
  apiSecret <- mkSecret . pack <$> getEnv "ERPNEXT_API_SECRET"

  let config = mkConfig url apiKey apiSecret
  manager <- newTlsManager

  -- Explicitly name the doctype to fetch, "DocType" in this example:
  Ok _ jsonResponse _ <- Simple.getDoc manager config "DocType" "Task"
  putStrLn $ showJsonPretty jsonResponse

  -- Define a DocType. Use :{ and :} in GHCi to paste multi-line Haskell code.
  data Customer = Customer
    { name :: Text
    , customer_name :: Text
    } deriving (Show, Generic)
  instance FromJSON Customer
  instance IsDocType Customer where
    docTypeName = "Customer"
    docName = name

  -- Get a customer, infer doctype via type system:
  Ok _ jsonResponse parsedCustomer <- Client.getDoc @Customer manager config "Company A"
  print parsedCustomer
  print $ docName parsedCustomer

  -- Get a filtered list of customers, infer doctype via type system:
  Ok _ jsonResponse parsedCustomerList <- Client.getDocList @Customer manager config [Fields ["name", "customer_name"], AndFilter [Like "name" "%Test%"]]
  print parsedCustomerList

#+end_src

** Advanced example use

#+begin_src haskell :tangle example2.hs
  {-# LANGUAGE OverloadedStrings #-}
  {-# LANGUAGE OverloadedRecordDot #-}
  {-# LANGUAGE DuplicateRecordFields #-}

  import ERPNext.Client
  import ERPNext.Client.Filter as Filter
  import ERPNext.Client.QueryStringParam
  import System.Environment
  import Data.Text (Text, pack, unpack, intercalate)
  import Network.HTTP.Client.TLS
  import Data.Aeson
  import GHC.Generics

  data Customer = Customer
    { name :: Text
    , customer_name :: Text
    } deriving Generic

  instance FromJSON Customer
  instance IsDocType Customer where
    docTypeName = "Customer"
    docName = error "not implemented"

  data SalesOrder = SalesOrder
    { name :: Text
    , customer :: Text
    } deriving Generic

  instance FromJSON SalesOrder
  instance IsDocType SalesOrder where
    docTypeName = "Sales Order"
    docName = error "not implemented"

  main :: IO ()
  main = do
    url <- pack <$> getEnv "ERPNEXT_BASE_URL" -- e.g. "https://my-erpnext.frappe.cloud/api"
    apiKey <- pack <$> getEnv "ERPNEXT_API_KEY"
    apiSecret <- mkSecret . pack <$> getEnv "ERPNEXT_API_SECRET"

    let cfg = mkConfig url apiKey apiSecret
    mgr <- newTlsManager

    -- Get all customers with given customer name:
    customersRes <- getDocList @Customer mgr cfg [Fields ["name", "customer_name"], AndFilter [Filter.Eq "customer_name" "Test Customer"]]
    case customersRes of
      Ok _ _ customers -> putStrLn $ show (length customers) ++ " customer(s)"
      err  -> putStrLn $ "error: \n" ++ showJsonResponsePretty err

    -- Get customer linked to sales order:
    let andThenWithCustomer = andThenWith (\o -> o.customer)
    (salesOrderRes, mCustomerRes) <- getDoc @SalesOrder mgr cfg "SAL-ORD-2026-00002"
                                `andThenWithCustomer` getDoc @Customer mgr cfg
    case (salesOrderRes, mCustomerRes) of
      (Ok _ _ salesOrder, Just (Ok _ _ customer)) -> putStrLn $ unpack salesOrder.name ++ ": " ++ unpack customer.customer_name
      (x, my) -> putStrLn $ "error: \n" ++ showJsonResponsePretty x ++ "\n" ++ maybe "" showJsonResponsePretty my

    res <- getAllFieldnames @Customer mgr cfg
    case res of
      Ok _ _ fieldnames -> putStrLn $ unpack $ intercalate ", " (take 5 fieldnames) <> ", ..."
      err -> putStrLn $ "error: \n" ++ showJsonResponsePretty res
#+end_src

#+begin_src sh
  . .env
  stack runhaskell --package http-client-tls example2.hs
#+end_src

** Remote Method Calls
ERPNext's REST API also supports calling
[[https://docs.frappe.io/framework/user/en/api/rest#remote-method-calls][remote
methods]] directly.

#+begin_src haskell
  getMethodCall  :: Manager -> Config -> MethodName -> Args -> IO (ApiResponse a)
  postMethodCall :: Manager -> Config -> MethodName -> Args -> IO (ApiResponse a)
#+end_src

- get for read-only, post for methods with db writes
- on python exception: =exc=, =exc_type=
- on success: =message= containing return value as JSON response

#+begin_src haskell :tangle example3.hs
  {-# LANGUAGE OverloadedStrings #-}
  {-# LANGUAGE TypeApplications #-}

  import ERPNext.Client
  import System.Environment
  import Data.Text (Text, pack, unpack)
  import Network.HTTP.Client.TLS

  main :: IO ()
  main = do
    url <- pack <$> getEnv "ERPNEXT_BASE_URL"
    apiKey <- pack <$> getEnv "ERPNEXT_API_KEY"
    apiSecret <- mkSecret . pack <$> getEnv "ERPNEXT_API_SECRET"

    let cfg = mkConfig url apiKey apiSecret
    mgr <- newTlsManager

    -- Read-only remote method call:
    userRes <- getMethodCall @Text mgr cfg "frappe.auth.get_logged_user" []
    case userRes of
      Ok _ _ user -> putStrLn $ "Logged in as: " ++ unpack user
      err -> putStrLn $ "error: \n" ++ showJsonResponsePretty err

    -- Remote method call that writes to the database:
    tagRes <- postMethodCall @Text mgr cfg "frappe.desk.doctype.tag.tag.add_tag"
                [ ("dt", Just "Issue")
                , ("dn", Just "ISS-2026-00001")
                , ("tag", Just "example tag")
                ]
    case tagRes of
      Ok _ _ _ -> putStrLn "Tag added."
      err -> putStrLn $ "error: \n" ++ showJsonResponsePretty err
#+end_src

#+begin_src sh
  . .env
  stack runhaskell --package http-client-tls example3.hs
#+end_src

questions:

1. reuse ApiResponse type? it currently doesn't handle exceptions
   explicitly but it might be useful.
2. how to pass args to method calls?
3. how to pass the method name? =IsMethodCall[Result]= class? or explicitly?
4. how to handle possible return value variants?
   like ~data CallRes1 = Found Int | NotFound String~.
   could be done by just 1 variant (and the models approach) with
   null-able fields.

proposals:

1. pass method name explicitly
2. reuse =ApiResponse= (no explicit handling of exceptions because
   most exceptions are probably triggered by invalid params)
3. no =IsMethodCall= class because there might often be primitive
   return types like a number or a string. wrapping these with newtype
   only to implement instances for them is too much.

** Scope and Limits

- Only [[https://docs.frappe.io/framework/user/en/api/rest#1-token-based-authentication][token-based authentication]] is supported.
- [[https://docs.frappe.io/framework/user/en/api/rest#file-uploads][File Uploads]] are not yet supported.

** Data records for DocTypes

Haskell record types for the DocTypes can be coded by hand which
requires some boilerplate like Aeson instances, handling =null= or
missing values, and writing helper functions like =mkCustomer=.

This library provides tooling to generate Haskell record types from a
simple DSL very similar to
[[https://hackage.haskell.org/package/persistent/docs/Database-Persist-Quasi.html][persistent's model definition syntax]].

1. A script generates an [[https://swagger.io/specification/][OpenAPI Specification]] file in =yaml= format
   from your models file.
2. The [[https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/][Haskell-OpenAPI-Client-Code-Generator]] generates an Haskell API
   client, from which only the type definitions can be used.

The resulting files are a separate Haskell package which can be added
as a dependency. The resulting record types can be used together with
this API client but the =IsDocType= instance must still be defined by hand.

*Note: The API client part generated from the OpenAPI spec can not be used.*

Example models file:

#+begin_src plain :tangle models
  SalesOrder
    name Text
    total Double
    transaction_date Text
    items [SalesOrderItem]
    Required name

  SalesOrderItem
    name Text
    Required name

  Item
    item_code Text
    item_name Text
    item_group Text
    default_warehouse Text
    country_of_origin Text
    disabled Int
    is_purchase_item Int
    is_sales_item Int
    is_stock_item Int
    stock_uom Text
    Required item_code item_name is_purchase_item is_sales_item is_stock_item
#+end_src

#+begin_example
$ ./scripts/gen-openapi-yaml.sh models > openapi.yaml
$ openapi3-code-generator-exe \
    --specification openapi.yaml \
    --package-name erpnext-api-client-models \
    --module-name ERPNextAPI \
    --force --output-dir api-client/
$ tree api-client/
api-client/
├── erpnext-api-client-models.cabal
├── src
│   ├── ERPNextAPI
│   │   ├── Common.hs
│   │   ├── Configuration.hs
│   │   ├── Operations
│   │   │   └── DummyOperation.hs
│   │   ├── SecuritySchemes.hs
│   │   ├── TypeAlias.hs
│   │   ├── Types     <---- here are the generated types
│   │   │   ├── SalesOrder.hs
│   │   │   ├── SalesOrderItem.hs
│   │   │   ├── Item.hs
│   │   └── Types.hs
│   └── ERPNextAPI.hs
└── stack.yaml
#+end_example

To include the generated model types in your stack project:

Add to your =stack.yaml=:

: extra-deps:
: - …
: - ./api-client/

In your =package.yaml=:

: dependencies:
: - …
: - erpnext-api-client-models

In your Haskell code:

#+begin_src haskell
  import ERPNext.Client -- the erpnext-api-client
  import ERPNextAPI.Types -- the generated types

  …

  -- And here some orphan instances:

  instance IsDocType SalesOrder where
    docTypeName = "Sales Order"

  instance IsDocType Customer where
    docTypeName = "Customer"
#+end_src

*** Notes on =Maybe= and =Nullable=

In the DocType definition model,

- =Maybe= becomes =Nullable= meaning that the field value can be =null= (or
  =Null= in Haskell).

- Fields *not* listed after =Required= become =Maybe= meaning that the fields
  are optional and =Nothing= will be left out in the JSON representation.

Type level:

: Project
:   name Text
:   project_name Text
:   status Text
:   project_type Text Maybe
:   Required name project_name
:
: data Project = Project
:   { projectName :: Text
:   , projectProject_name :: Text
:   , projectStatus :: Maybe Text
:   , projectProject_type :: Maybe (Nullable Text)
:   } deriving (Show, Eq)
:
: data ProjectPartial = ProjectPartial
:   { projectPartialName :: Maybe Text
:   , projectPartialProject_name :: Maybe Text
:   , projectPartialStatus :: Maybe Text
:   , projectPartialProject_type :: Maybe (Nullable Text)
:   } deriving (Show, Eq)

For each DocType, two types are generated, e.g. =Project= and
=ProjectPartial=.
The =*Partial= version has no required fields i.e. all fields are
=Maybe= and are left out when assigned to =Nothing=.

Value level:

: Project                                             {
:   { projectName = "PROJ-001"                          "name": "PROJ-001",
:   , projectProject_name = "My Project"      =>        "project_name": "My Project",
:   , projectStatus = Nothing
:   , projectProject_type = Just Null                   "project_type": null
:   }                                                 }


: mkProjectPartial                                    {
:   { projectProject_name = Just "My Project 2"   =>    "project_name": "My Project"
:   }                                                 }

** Note on TLS problems

If you're running ERPNext in your test environment, chances are that your
server does not have a valid TLS certificate signed by a trusted CA.

In this case you can configure the HTTP connection manager's TLS
settings like this:

#+begin_src haskell
  import Network.HTTP.Client.TLS (mkManagerSettings)
  import Network.Connection (TLSSettings (..))

  …

  let tlsSettings =
        mkManagerSettings
          ( TLSSettingsSimple
              { settingDisableCertificateValidation = True
              }
          )
          Nothing
  manager <- Network.HTTP.Client.newManager tlsSettings
  …
#+end_src

Edit the example code from the first section accordingly and run it with:

#+begin_src sh
  stack runhaskell --package crypton-connection --package http-client-tls example1.hs
#+end_src
